### ISSUE TITLE
Error with new sequoia image

### ISSUE THREAD

**Issue by matzuk** [cirruslabs/tart#883]
Hey folks,

I wanted to try a Virtual machine with the new MacOS version on the board.
Pulling was successful: `docker pull ghcr.io/cirruslabs/macos-sequoia-vanilla:15.1-beta-1`
However, any attempt to run or clone this VM fails with the following error:
```
Error: dataCorrupted(Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "hardwareModel", intValue: nil)], debugDescription: "", underlyingError: nil))
```
The Host's MacOS version is `14.4.1`.

**Comment by matzuk** [comment]
@edigaryev I guess it should be fixed, but it is not. Right? Am I doing something wrong?

**Comment by fkorotkov** [comment]
We started building the images on Sequoia again to support Apple Login (see #722). Since there is a public beta now we decided to switch.

You can download the [`*.ipsw` for Sequoia](https://github.com/cirruslabs/macos-image-templates/blob/master/templates/vanilla-sequoia.pkr.hcl#L11) and build it locally via `tart create --from-ipsw UniversalMac_15.1_24B5009l_Restore.ipsw sequpia`

**Comment by matzuk** [comment]
@fkorotkov got it, thank you!

**Comment by iby** [comment]
Should building work on Sonoma, though? I can't seem to run the latest OCI, nor I can build my own… 🤔

```
tart create --from-ipsw UniversalMac_15.1_24B5024e_Restore.ipsw seq1
Installing OS...
0%
Error: A software update is required to complete the installation. Installation requires a software update.
```

Just updated Sonoma to latest stable release – still getting the `software update` error.

**Comment by edigaryev** [comment]
@iby you need to install latest version of Xcode. 16.1 beta worked for me.

See https://github.com/cirruslabs/tart/issues/514 for more details.

**Comment by iby** [comment]
@edigaryev thanks for the tip! Sounds like there's no way to run the latest Sequoia on Sonoma? Or am I missing something?

I'm wondering, because earlier Sequoia versions could be ran on Sonoma… but we couldn't upgrade from within guest because it was lacking a restore partition… so, if I create an older version from IPSW with restore partition and upgrade to the latest Beta? Or is there a more straight forward approach?

**Comment by edigaryev** [comment]
> The installation of `UniversalMac_15.1_24B5024e_Restore.ipsw`, however, seems to crash with the following entry in the Console app:

This seems to be now fixed in 15.1 beta 3 (`24B5035e`) and the installation works just fine on Sonoma.

**Comment by Destrocamil** [comment]
@edigaryev where did you get the ipsw for the 15.1 beta 3?
